id: A7FDA30AA
title: CVI_Verses 165-184
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 21:27:38.908982
  last_modified_at: 2022-03-01 21:27:38.908985
