id: A7FDA30AA
title: CIII_23th Pratītyasamutpāda
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 21:27:38.779383
  last_modified_at: 2022-03-01 21:27:38.779386
