id: A7FDA30AA
title: CVII_Maitreya
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 21:27:38.891699
  last_modified_at: 2022-03-01 21:27:38.891702
