id: A7FDA30AA
title: CVII_Verses 233-238
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 21:27:38.893367
  last_modified_at: 2022-03-01 21:27:38.893370
