id: A7FDA30AA
title: CIII_34th Sāgaramudrāsamādhi
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 21:27:38.794910
  last_modified_at: 2022-03-01 21:27:38.794913
