id: A7FDA30AA
title: CIV_Pāramitāvarṣa
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 21:27:38.878534
  last_modified_at: 2022-03-01 21:27:38.878538
