id: A7FDA30AA
title: CIII_Verses 67-76
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 21:27:38.842520
  last_modified_at: 2022-03-01 21:27:38.842523
