id: A7FDA30AA
title: CIII_12th Tyāgānusmṛti
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 21:27:38.761335
  last_modified_at: 2022-03-01 21:27:38.761341
